<a href="https://colab.research.google.com/github/2303A52487/GEN-AI/blob/main/GEN_AI_Assignment_8_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from tensorflow import keras
from tensorflow.keras import layers

# Load Dataset
dataset_path = ('/content/winequality-red.csv')  # Adjust this if necessary
df = pd.read_csv(dataset_path)

# Data Preprocessing
X = df.drop('quality', axis=1)
y = df['quality']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Build ANN Model
model = keras.Sequential([
    layers.Dense(16, activation='relu', input_shape=(X_train.shape[1],)),
    layers.Dense(20, activation='relu'),
    layers.Dense(25, activation='relu'),
    layers.Dense(10, activation='relu'),
    layers.Dense(1, activation='linear')
])

model.compile(optimizer='Adadelta', loss='mean_squared_error', metrics=['accuracy'])

# Train Model
history = model.fit(X_train, y_train, epochs=100, batch_size=64, validation_split=0.2)

# Evaluate Model
y_train_pred = np.round(model.predict(X_train))
y_test_pred = np.round(model.predict(X_test))

train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

print(f"Training Accuracy: {train_accuracy:.4f}")
print(f"Testing Accuracy: {test_accuracy:.4f}")

# Confusion Matrix and Classification Report
conf_matrix = confusion_matrix(y_test, y_test_pred)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", classification_report(y_test, y_test_pred))

# Save Model
model.save('wine_quality_model.h5')
print("Model saved as wine_quality_model.h5")

# Load and Deploy Model
def predict_quality(features):
    loaded_model = keras.models.load_model('wine_quality_model.h5')
    features_scaled = scaler.transform([features])
    prediction = loaded_model.predict(features_scaled)
    print(f"Predicted Wine Quality: {round(prediction[0][0])}")

# Example Prediction
example_features = X_test[0]
predict_quality(example_features)


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - accuracy: 0.0000e+00 - loss: 35.3025 - val_accuracy: 0.0000e+00 - val_loss: 35.3922
Epoch 2/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0000e+00 - loss: 35.3451 - val_accuracy: 0.0000e+00 - val_loss: 35.3817
Epoch 3/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0000e+00 - loss: 35.6012 - val_accuracy: 0.0000e+00 - val_loss: 35.3712
Epoch 4/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0000e+00 - loss: 35.3228 - val_accuracy: 0.0000e+00 - val_loss: 35.3606
Epoch 5/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0000e+00 - loss: 35.3577 - val_accuracy: 0.0000e+00 - val_loss: 35.3499
Epoch 6/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0000e+00 - loss: 35.3526 - val_accuracy: 0.0000e+00 - val_loss: 35.3392
Epoch 7/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0000e+00 - loss: 35.2159 - val_accuracy: 0.0000e+00 - val_loss: 35.3284
Epoch 8/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_

Training Accuracy: 0.0000
Testing Accuracy: 0.0000
Confusion Matrix:
 [[  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   1   0   0   0   0   0   0]
 [  0  10   0   0   0   0   0   0]
 [ 17 113   0   0   0   0   0   0]
 [ 16 116   0   0   0   0   0   0]
 [  7  35   0   0   0   0   0   0]
 [  0   5   0   0   0   0   0   0]]
Classification Report:
               precision    recall  f1-score   support

        -1.0       0.00      0.00      0.00       0.0
        -0.0       0.00      0.00      0.00       0.0
         3.0       0.00      0.00      0.00       1.0
         4.0       0.00      0.00      0.00      10.0
         5.0       0.00      0.00      0.00     130.0
         6.0       0.00      0.00      0.00     132.0
         7.0       0.00      0.00      0.00      42.0
         8.0       0.00      0.00      0.00       5.0

    accuracy                           0.00     320.0
   macro avg       0.00      0.00      0.00     320.0
weighted avg       0.00      

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step
Predicted Wine Quality: 16
